KingCourier/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("login.urls")),
    path('', include("GestionClientes.urls")),
    path('welcome/', TemplateView.as_view(template_name='welcome.html'), name='welcome'),
    path('mensajeros/', include("GestionMensajeros.urls")),
    path('pedidos/', include("GestionPedidos.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from login import views
from user.views import user_create, users_list, edit_profile, eliminar_usuario

urlpatterns = [
    path('', views.login_user, name='login'),
    path('users/', users_list, name='users'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfil/edit', edit_profile, name='editar_perfil'),
    path('users/create', user_create, name='register'),
    path('logout/', views.log_out, name='logout'),
    path('users/user/<int:user_id>/eliminar/', eliminar_usuario, name='eliminar_usuario'),
]

GestionClientes/models.py
from django.db import models
from GestionMensajeros.models import Mensajeros
# Create your models here.


class Cliente(models.Model):
    identificacion = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    ciudad = models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre


class Sucursale(models.Model):
    nombre = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    ciudad = models.CharField(max_length=100)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class DetalleClienteMensajeros(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    mensajero = models.ForeignKey(Mensajeros, on_delete=models.CASCADE)

    def __str__(self):
        return self.cliente.nombre + " - " + self.mensajero.nombre

GestionPedidos/models.py
from django.db import models
from GestionMensajeros.models import Mensajeros
from GestionClientes.models import Cliente, Sucursale
from django.utils import timezone
# Create your models here.


class Pedido(models.Model):
    id_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    id_mensajero = models.ForeignKey(Mensajeros, on_delete=models.CASCADE)
    id_sucursal_origen = models.ForeignKey(Sucursale, on_delete=models.CASCADE, related_name='sucursal_origen')
    id_sucursal_destino = models.ForeignKey(Sucursale, on_delete=models.CASCADE, related_name='sucursal_destino')
    descripcion = models.CharField(max_length=100)
    tipo_trasnporte = models.CharField(max_length=20)
    numero_paquetes = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True, editable=True)
   
    def __str__(self):
        return str(self.id_cliente) + " - " + str(self.id_mensajero)
    
class EstadoPedido(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class DetalleEstadoPedido(models.Model):
    id_estado = models.ForeignKey(EstadoPedido, on_delete=models.CASCADE)
    id_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    fecha_hora = models.DateTimeField(auto_now=False, auto_now_add=False)
    foto = models.ImageField(upload_to='detalles_estado', null=True, blank=True)
    def __str__(self):
        return str(self.id_estado)+ " - " + str(self.id_pedido)

frontend/templates/mensajeros/clientes.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block head %}
    <title>King Courier | Clientes Asociados</title>
    <link href="{% static 'styles/detailClientesStyle.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
<div class="contenedor">
    <div class="tarjeta">
      <h2>Clientes Asociados</h2>
      {% for cliente in clientes %}
      <p>{{cliente.nombre}}</p>
      {% endfor %}
    </div>
  
  </div>

{% endblock content %}

frontend/templates/mensajeros/create.html
{% extends 'layouts/base.html' %} 
{% load static %} 

{% block head %}
  <title>King Courier | Crear Mensajero</title>
  <link href="{% static 'styles/FormStyle.css' %}" rel="stylesheet" />
{% endblock head %} 

{% block content %}

  <h1 class="titulo">Crear Mensajero</h1>
  {{error}}
  <form action="{% url 'create_mensajeros' %}" method="POST">
    {% csrf_token %}
    {{createForm}}
    {% comment %} <label for="id_identificacion">Identificacion:</label>
    <input type="text" name="identificacion" maxlength="20" required="" id="id_identificacion"/>

    <label for="id_nombre">Nombre:</label>
    <input type="text" name="nombre" maxlength="200" required="" id="id_nombre" />

    <label for="id_direccion">Direccion:</label>
    <input type="text" name="direccion" maxlength="200" required="" id="id_direccion"/>

    <label for="id_ciudad">Ciudad:</label>
    <input type="text" name="ciudad" maxlength="100" required="" id="id_ciudad" />

    <label for="id_email">Email:</label>
    <input type="email" name="email" maxlength="254" required="" id="id_email" />

    <label for="id_telefono">Telefono:</label>
    <input type="text" name="telefono" maxlength="20" required="" id="id_telefono"/>
    {% endcomment %}
    
    <button>Guardar</button> 
  </form>

{% endblock content %}

frontend/templates/mensajeros/detail.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block head %}
    <title>King Courier | Informacion del Mensajero</title>
    <link href="{% static 'styles/detailClientesStyle.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
<div class="contenedor">
    <div class="tarjeta">
      <h2>Detalles del mensajero</h2>
      <p>Identificacion: {{ mensajero.identificacion }}</p>
      <p>Nombre: {{ mensajero.nombre }}</p>
      <p>Direccion: {{ mensajero.direccion }}</p>
      <p>Ciudad: {{ mensajero.ciudad }}</p>
      <p>Email: {{ mensajero.email }}</p>
      <p>Telefono: {{ mensajero.telefono }}</p>
      <p>Ciudad: {{ mensajero.ciudad }}</p>
      <p>Vehiculo: {{ mensajero.vehiculo }}</p>
    </div>
  
    <div class="tarjeta">
      <h2>Clientes Asociados</h2>
      {% for detalle_cliente in detalle_clientes %}
        <p>{{detalle_cliente.cliente}}</p>
      {% endfor %}
    </div>
  
  </div>

{% endblock content %}

frontend/templates/mensajeros/edit.html
{% extends 'layouts/base.html' %} 

{% load static %}

{% block head %}
  <title>King Courier | Editar Mensajero</title>
  <link href="{% static 'styles/FormStyle.css' %}" rel="stylesheet" />
{% endblock head %} 

{% block content %}
<h1 class="titulo">Editar Mensajero</h1>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Guardar Cambios</button>
</form>
{% endblock content %}

frontend/templates/mensajeros/index.html
{% extends 'layouts/base.html' %} 
{% load static %}

{% block head %}
    <title>King Courier | Mensajeros</title>
    <link href="{% static 'styles/TableStyle.css' %}" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'scripts/SearchTable.js' %}"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% endblock head %}

{% block header %}
    {% include 'layouts/navbar.html' %}
{% endblock header %}

{% block content %}
  <h1 class="text-center">Mensajeros</h1>
    {% if message %}
      <div class="alert alert-info" role="alert">
        {{message}}
      </div>
    {% endif %}
    
      <div class="search-container d-flex justify-content-between align-items-center mb-3">
        <div class="mr-4 ml-4 btnCreate">
          <a class="btn btn-success w-150" href="{% url 'create_mensajeros' %}" role="button">Crear Mensajero</a>
        </div>
        <div class="mr-4 search">
          <input type="text" class="form-control w-300" id="search-input" placeholder="Buscar...">
        </div>
      </div>

      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Identificacion</th>
                <th>Nombre</th>
                <th>Direccion</th>
                <th>Ciudad</th>
                <th>Email</th>
                <th>Telefono</th>
                <th>Vehiculo</th>
                <th>Opciones</th>
              </tr>
            </thead>
            <tbody>
              {% for mensajero in mensajeros %}
                <tr>
                  <td>{{mensajero.identificacion}}</td>
                  <td><a href="{% url 'detalle_mensajero' mensajero.id %}">{{ mensajero.nombre }}</a></td>
                  <td>{{mensajero.direccion}}</td>
                  <td>{{mensajero.ciudad}}</td>
                  <td>{{mensajero.email}}</td>
                  <td>{{mensajero.telefono}}</td>
                  <td>{{mensajero.vehiculo}}</td>
                  <td> 
                    <a class="btn btn-info" href="{% url 'editar_mensajero' mensajero.id %}" role="button">Editar</a>             
                    {% comment %} <a class="btn btn-danger" href="{% url 'eliminar_mensajero' mensajero.id %}" role="button" onclick="return confirm('¿Estás Seguro de Borrar este Mensajero?')">Borrar</a> {% endcomment %}
                    <button class="btn btn-danger" data-toggle="modal" data-target="#confirmModal{{ mensajero.id }}">Borrar</button>
                  </td>
                </tr>

                <div class="modal fade" id="confirmModal{{ mensajero.id }}" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="confirmModalLabel">
                          <i class='bx bx-message-rounded-error bx-tada bx-lg' style='color:#DC3545'  ></i>
      
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        ¿Estás Seguro de Borrar este Mensajero?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <a class="btn btn-danger" href="{% url 'eliminar_mensajero' mensajero.id %}">Borrar</a>
                      </div>
                    </div>
                  </div>
                </div>



              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

{% endblock content %}